### ISSUE TITLE
Missing pyaml dependency in server.py for container 1.0

### ISSUE THREAD

**Issue by slbryson** [devopstales/kube-openid-connect#10]
Server throws an error when running
docker run -it devopstales/kube-openid-connector:latest
Traceback (most recent call last):
  File "/opt/server.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

Added pyaml in the Dockerfile for local build
RUN pip3 install pyaml flask requests_oauthlib requests flask_cors

**Comment by Blaiserman** [comment]
The label latest and 1.1 is a metadata label that pointed to a wrong version. I updated it.

**Comment by devopstales** [comment]
Image is updated and fixed.

**Comment by slbryson** [comment]
Excellent. Let's close this please include the change description in release notes.
