### ISSUE TITLE
Readme Updates Required

### ISSUE THREAD

**Issue by slbryson** [devopstales/kube-openid-connect#11]
Please reconcile the name of the binary and the commands with the documentation.
In the Documentation section

-   Include a link to find the values.yaml file referenced in the command example.  
-   Consider indicating the minimal amount of updates to the values.yaml file for a working solution.

In the Deployment section
Is it dtlogin?  openid-connect?  ? Krew has no plugin called openid-connect.  I see a plan in the Project space to update these.

Please provide the *correct* command to actually run the plugin today.
kubectl login <-- is not valid
should it be 
kubectl dtlogin ???

**Comment by devopstales** [comment]
I updated the README. The plugin is `kubectl login` but krew forced me to change it to dtlogin.
