### ISSUE TITLE
Problems running dtlogin plugin

### ISSUE THREAD

**Issue by slbryson** [devopstales/kube-openid-connect#9]
Error:
 kubectl dtlogin
/home/sbryson/.krew/bin/kubectl-dtlogin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/sbryson/.krew/bin/kubectl-dtlogin)
/home/sbryson/.krew/bin/kubectl-dtlogin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/sbryson/.krew/bin/kubectl-dtlogin)

Using microk8s latest stable

**Comment by devopstales** [comment]
@slbryson This issue has nothing to do with your kubernetes version but with your Linux version. I will check the build to disable the C version dependency to use pure GO. like this: https://stackoverflow.com/questions/64421305/heroku-go-app-crashes-version-glibc-2-32-not-found-required-by-bin-main

**Comment by slbryson** [comment]
I was trying to describe my environment. 
Ok I'm using Ubuntu 20.2
After you adjust the build, what do I need to do?

**Comment by devopstales** [comment]
@slbryson There will be a new release and update to hat.

**Comment by devopstales** [comment]
@slbryson I updated a new release binary to this repo: https://github.com/devopstales/kube-openid-connect/releases/tag/client_v1.1
This is not on krew yet. Please try it. I tested this and the previous version and bot worked for me on Ubuntu 22.04

**Comment by slbryson** [comment]
Excellent, I will test and let you know

**Comment by slbryson** [comment]
On the issue with the server, I may not be correctly passing Env variables into the pod. I am populating the values.yaml file, but I need to check the helm chart template to see if they are getting mapped correctly.
I ran the server outside of K8 and with a few modifications it ran.

**Comment by devopstales** [comment]
@slbryson If you have other problems please open a separate issue. This is for the client problem? Is the new version working for you? If so I will close this issue and upload the new cli version to krew.

**Comment by slbryson** [comment]
That's right. Let's close this issue and use the new version
